### ISSUE TITLE
[JUnit Results] Tests run: 17,  Failures: 11

### ISSUE THREAD

**Issue by katsoohoo** [huyenng1220/cs152#1]
Looks like you did a bunch of work already. I will debug your code and and fix the failures!

**Comment by huyenng1220** [comment]
the failures are mainly because of the undone methods. I'll try to work on it more later.

**Comment by katsoohoo** [comment]
You did a lot already, so I can finish them for you :)

**Comment by katsoohoo** [comment]
All tests passed.
